// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ZY8fh8DplPGvhEt1zGBCYW6wnmEon5c',
    appId: '1:520100424312:web:5ccad4b98d424f00cb9b8d',
    messagingSenderId: '520100424312',
    projectId: 'barber-c61c5',
    authDomain: 'barber-c61c5.firebaseapp.com',
    storageBucket: 'barber-c61c5.firebasestorage.app',
    measurementId: 'G-3XNGVNTH03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAejJRIXNIE-rxCTJhNISn4OIhr_RVK8_k',
    appId: '1:520100424312:android:018b84195249f2abcb9b8d',
    messagingSenderId: '520100424312',
    projectId: 'barber-c61c5',
    storageBucket: 'barber-c61c5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRLz-l4cKE3ILay63jdER2TxNdF94Eu0Y',
    appId: '1:520100424312:ios:daff3055da3c4fcbcb9b8d',
    messagingSenderId: '520100424312',
    projectId: 'barber-c61c5',
    storageBucket: 'barber-c61c5.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRLz-l4cKE3ILay63jdER2TxNdF94Eu0Y',
    appId: '1:520100424312:ios:daff3055da3c4fcbcb9b8d',
    messagingSenderId: '520100424312',
    projectId: 'barber-c61c5',
    storageBucket: 'barber-c61c5.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_ZY8fh8DplPGvhEt1zGBCYW6wnmEon5c',
    appId: '1:520100424312:web:ca5d39cc392966d4cb9b8d',
    messagingSenderId: '520100424312',
    projectId: 'barber-c61c5',
    authDomain: 'barber-c61c5.firebaseapp.com',
    storageBucket: 'barber-c61c5.firebasestorage.app',
    measurementId: 'G-4T5Q75MZ3P',
  );
}
