// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvbj7Ww-OzuQiND_ccNIh0SyrepFrcBs',
    appId: '1:715905788902:web:8f6cc48fb4190feb0ec427',
    messagingSenderId: '715905788902',
    projectId: 'barber-5082f',
    authDomain: 'barber-5082f.firebaseapp.com',
    storageBucket: 'barber-5082f.firebasestorage.app',
    measurementId: 'G-MCKX97H52Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUZqrDqSUEHIhddya3A06zFYHxBJgImA4',
    appId: '1:715905788902:android:eb4c7aab17be35790ec427',
    messagingSenderId: '715905788902',
    projectId: 'barber-5082f',
    storageBucket: 'barber-5082f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgkHpBJgzsjzXepNCWh4ckNCU-8ltCSyk',
    appId: '1:715905788902:ios:19a3c313ff11643c0ec427',
    messagingSenderId: '715905788902',
    projectId: 'barber-5082f',
    storageBucket: 'barber-5082f.firebasestorage.app',
    iosClientId: '715905788902-o6qnsn29ii6l4f6krlbsb7s3gv9gcfdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.barber',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgkHpBJgzsjzXepNCWh4ckNCU-8ltCSyk',
    appId: '1:715905788902:ios:19a3c313ff11643c0ec427',
    messagingSenderId: '715905788902',
    projectId: 'barber-5082f',
    storageBucket: 'barber-5082f.firebasestorage.app',
    iosClientId: '715905788902-o6qnsn29ii6l4f6krlbsb7s3gv9gcfdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBvbj7Ww-OzuQiND_ccNIh0SyrepFrcBs',
    appId: '1:715905788902:web:233e5ebfe82477670ec427',
    messagingSenderId: '715905788902',
    projectId: 'barber-5082f',
    authDomain: 'barber-5082f.firebaseapp.com',
    storageBucket: 'barber-5082f.firebasestorage.app',
    measurementId: 'G-0L9QFKRD73',
  );
}
